/**
 * Shared type definitions for the YouTube Subtitles MCP server.
 */

// ── YouTube API types ──

export interface SubtitleSegment {
  utf8: string;
}

export interface SubtitleEvent {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: SubtitleSegment[];
}

export interface YouTubeTimedTextResponse {
  events?: SubtitleEvent[];
  wireMagic?: string;
}

export interface CaptionTrack {
  baseUrl: string;
  name?: {
    simpleText?: string;
    runs?: Array<{ text: string }>;
  };
  languageCode: string;
  kind?: string;          // 'asr' for auto-generated
  isTranslatable?: boolean;
}

export interface TranslationLanguage {
  languageCode: string;
  languageName?: {
    simpleText?: string;
    runs?: Array<{ text: string }>;
  };
}

export interface PlayerCaptionsTracklistRenderer {
  captionTracks?: CaptionTrack[];
  translationLanguages?: TranslationLanguage[];
}

export interface PlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: PlayerCaptionsTracklistRenderer;
  };
  videoDetails?: {
    videoId: string;
    title: string;
    lengthSeconds: string;
    channelId: string;
    author: string;
  };
}

// ── Processed output types ──

export interface LanguageInfo {
  code: string;
  name: string;
  kind: 'manual' | 'auto-generated';
  isTranslatable: boolean;
}

export interface SubtitleEntry {
  index: number;
  startMs: number;
  endMs: number;
  startFormatted: string;
  endFormatted: string;
  text: string;
}

export interface SubtitleResult {
  videoId: string;
  videoTitle: string;
  language: string;
  languageName: string;
  kind: 'manual' | 'auto-generated';
  entries: SubtitleEntry[];
  totalEntries: number;
  format: 'json' | 'srt' | 'txt';
  formatted?: string;      // Populated when format is 'srt' or 'txt'
}

export interface LanguageListResult {
  videoId: string;
  videoTitle: string;
  manual: LanguageInfo[];
  autoGenerated: LanguageInfo[];
  translationLanguages: Array<{ code: string; name: string }>;
  totalAvailable: number;
}

// ── Error types ──

export class SubtitleError extends Error {
  constructor(
    message: string,
    public readonly code: string,
    public readonly statusCode?: number
  ) {
    super(message);
    this.name = 'SubtitleError';
  }
}

// ── Rate limiting ──

export interface RateLimitEntry {
  count: number;
  resetAt: number;
}

// ── Bridge API types ──

export interface BridgeHealthResponse {
  status: 'ok';
  version: string;
  uptime: number;
}

export interface BridgeErrorResponse {
  error: string;
  code: string;
}
