/**
 * Core YouTube subtitle extraction service.
 * Fetches player data via InnerTube API (no auth/cookies needed),
 * extracts caption tracks, and converts subtitle formats.
 */

import {
  YOUTUBE_VIDEO_URL_REGEX,
  getLanguageName,
} from './constants.js';
import { logger } from './logger.js';
import { getAutoSubtitle } from './auto-store.js';
import type {
  PlayerResponse,
  CaptionTrack,
  YouTubeTimedTextResponse,
  SubtitleEntry,
  SubtitleResult,
  LanguageListResult,
  LanguageInfo,
  SubtitleError as SubtitleErrorType,
} from './types.js';
import { SubtitleError } from './types.js';

// ── Helpers ──

export function extractVideoId(input: string): string {
  // Direct video ID (11 chars)
  if (/^[a-zA-Z0-9_-]{11}$/.test(input)) return input;

  const match = input.match(YOUTUBE_VIDEO_URL_REGEX);
  if (!match) {
    throw new SubtitleError(
      `Invalid YouTube URL or video ID: "${input}"`,
      'INVALID_INPUT'
    );
  }
  return match[1];
}

function formatTimeSRT(ms: number): string {
  const h = Math.floor(ms / 3600000);
  const m = Math.floor((ms % 3600000) / 60000);
  const s = Math.floor((ms % 60000) / 1000);
  const mmm = ms % 1000;
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')},${String(mmm).padStart(3, '0')}`;
}

// ── YouTube page scraping (same approach as the Chrome extension) ──

async function fetchPlayerResponse(videoId: string): Promise<PlayerResponse> {
  const pageUrl = `https://www.youtube.com/watch?v=${videoId}`;

  logger.debug('Fetching YouTube page', { videoId });

  const response = await fetch(pageUrl, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
      'Accept-Language': 'en-US,en;q=0.9',
    },
  });

  if (!response.ok) {
    throw new SubtitleError(
      `YouTube returned HTTP ${response.status}`,
      'YOUTUBE_API_ERROR',
      response.status
    );
  }

  const html = await response.text();

  // Extract ytInitialPlayerResponse from page — same method the extension uses
  // Use bracket-counting instead of regex to handle the large nested JSON correctly
  const marker = 'ytInitialPlayerResponse';
  const markerIdx = html.indexOf(marker);
  if (markerIdx === -1) {
    throw new SubtitleError(
      'Could not find player response in YouTube page',
      'PARSE_ERROR'
    );
  }

  // Find the opening brace after the marker
  const startIdx = html.indexOf('{', markerIdx);
  if (startIdx === -1) {
    throw new SubtitleError(
      'Could not extract player response from YouTube page',
      'PARSE_ERROR'
    );
  }

  // Count braces to find the matching closing brace
  let depth = 0;
  let endIdx = startIdx;
  for (let i = startIdx; i < html.length; i++) {
    if (html[i] === '{') depth++;
    else if (html[i] === '}') depth--;
    if (depth === 0) { endIdx = i; break; }
  }

  const jsonStr = html.substring(startIdx, endIdx + 1);

  let data: PlayerResponse;
  try {
    data = JSON.parse(jsonStr) as PlayerResponse;
  } catch {
    throw new SubtitleError(
      'Failed to parse player response JSON',
      'PARSE_ERROR'
    );
  }

  if (!data.videoDetails) {
    throw new SubtitleError(
      'Video not found or is unavailable',
      'VIDEO_NOT_FOUND'
    );
  }

  return data;
}

// ── Caption track extraction ──

function extractTrackDisplayName(track: CaptionTrack): string {
  if (track.name?.simpleText) return track.name.simpleText.replace(/\s*\(auto-generated\)\s*/i, '').trim();
  if (track.name?.runs?.[0]?.text) return track.name.runs[0].text.replace(/\s*\(auto-generated\)\s*/i, '').trim();
  return getLanguageName(track.languageCode);
}

function parseCaptionTracks(playerResponse: PlayerResponse): {
  tracks: CaptionTrack[];
  translationLanguages: Array<{ code: string; name: string }>;
} {
  const renderer = playerResponse.captions?.playerCaptionsTracklistRenderer;
  if (!renderer) {
    return { tracks: [], translationLanguages: [] };
  }

  const tracks = renderer.captionTracks || [];
  const translationLanguages = (renderer.translationLanguages || []).map((tl) => ({
    code: tl.languageCode,
    name: tl.languageName?.simpleText || tl.languageName?.runs?.[0]?.text || tl.languageCode,
  }));

  return { tracks, translationLanguages };
}

function buildUrlWithLanguage(baseUrl: string, targetLang?: string): string {
  const url = new URL(baseUrl);
  url.searchParams.set('fmt', 'json3');
  if (!targetLang) return url.toString();
  
  const isAutoGenerated = targetLang.startsWith('a-');
  const actualLangCode = isAutoGenerated ? targetLang.substring(2) : targetLang;
  
  const originalLang = url.searchParams.get('lang');
  url.searchParams.set('lang', actualLangCode);
  
  if (isAutoGenerated) {
    url.searchParams.set('kind', 'asr');
  } else {
    url.searchParams.delete('kind');
  }
  
  if (originalLang && originalLang !== actualLangCode && !isAutoGenerated) {
    url.searchParams.set('tlang', actualLangCode);
  } else {
    url.searchParams.delete('tlang');
  }
  
  return url.toString();
}

async function fetchTimedText(baseUrl: string, targetLang?: string): Promise<{
  data: YouTubeTimedTextResponse;
  actualLang: string;
  actualKind: string;
}> {
  const finalUrl = buildUrlWithLanguage(baseUrl, targetLang);
  logger.info('Fetching timed text', { url: finalUrl, baseUrl, targetLang });

  const response = await fetch(finalUrl, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
    },
  });
  if (!response.ok) {
    throw new SubtitleError(
      `Failed to fetch subtitles (HTTP ${response.status})`,
      'SUBTITLE_FETCH_ERROR',
      response.status
    );
  }

  const text = await response.text();
  let data: YouTubeTimedTextResponse;
  try {
    data = JSON.parse(text) as YouTubeTimedTextResponse;
  } catch (err) {
    logger.error('Failed to parse timedtext response', {
      responseLength: text.length,
      responseStart: text.substring(0, 200),
    });
    throw new SubtitleError(
      'Subtitle response was not valid JSON — YouTube may have returned XML or an error page',
      'PARSE_ERROR'
    );
  }

  const isAutoGenerated = targetLang?.startsWith('a-') || false;
  const actualLangCode = isAutoGenerated ? targetLang!.substring(2) : (targetLang || 'unknown');

  return {
    data,
    actualLang: actualLangCode,
    actualKind: isAutoGenerated ? 'asr' : 'manual',
  };
}

function parseEvents(data: YouTubeTimedTextResponse): SubtitleEntry[] {
  const entries: SubtitleEntry[] = [];
  let index = 1;

  for (const event of data.events || []) {
    if (!event.segs?.length) continue;
    const text = event.segs.map((s) => s.utf8 || '').join('').trim();
    if (!text) continue;

    const startMs = event.tStartMs || 0;
    const endMs = startMs + (event.dDurationMs || 0);

    entries.push({
      index: index++,
      startMs,
      endMs,
      startFormatted: formatTimeSRT(startMs),
      endFormatted: formatTimeSRT(endMs),
      text,
    });
  }

  return entries;
}

function formatAsSRT(data: YouTubeTimedTextResponse): string {
  let srt = '', i = 1;
  for (const e of data.events || []) {
    if (!e.segs?.length) continue;
    const text = e.segs.map(s => s.utf8 || '').join('').trim();
    if (!text) continue;
    srt += `${i++}\n${formatTimeSRT(e.tStartMs || 0)} --> ${formatTimeSRT((e.tStartMs || 0) + (e.dDurationMs || 0))}\n${text}\n\n`;
  }
  return srt;
}

function formatAsPlainText(data: YouTubeTimedTextResponse): string {
  const lines: string[] = [];
  let lastText = '';
  
  for (const e of data.events || []) {
    if (!e.segs?.length) continue;
    const text = e.segs.map(s => s.utf8 || '').join('').trim();
    if (!text || text === lastText) continue; // Skip duplicates
    
    // Clean up the text: remove musical notes and other special characters
    const cleanText = text
      .replace(/♪/g, '')
      .replace(/\[.*?\]/g, '') // Remove [Music], [Applause], etc.
      .trim();
    
    if (cleanText) {
      lines.push(cleanText);
      lastText = text;
    }
  }
  
  // Join lines and format paragraphs
  return lines.join(' ')
    .replace(/\s+/g, ' ') // Normalize spaces
    .replace(/([.!?])\s+/g, '$1\n\n') // Add paragraph breaks after sentences
    .trim();
}

// ── Public API ──

/**
 * List all available subtitle languages for a video.
 */
export async function listSubtitleLanguages(videoUrl: string): Promise<LanguageListResult> {
  const videoId = extractVideoId(videoUrl);
  const playerResponse = await fetchPlayerResponse(videoId);
  const { tracks, translationLanguages } = parseCaptionTracks(playerResponse);

  const manual: LanguageInfo[] = [];
  const autoGenerated: LanguageInfo[] = [];

  for (const track of tracks) {
    const info: LanguageInfo = {
      code: track.languageCode,
      name: extractTrackDisplayName(track),
      kind: track.kind === 'asr' ? 'auto-generated' : 'manual',
      isTranslatable: track.isTranslatable || false,
    };

    if (track.kind === 'asr') {
      autoGenerated.push(info);
    } else {
      manual.push(info);
    }
  }

  return {
    videoId,
    videoTitle: playerResponse.videoDetails?.title || 'Unknown',
    manual,
    autoGenerated,
    translationLanguages,
    totalAvailable: manual.length + autoGenerated.length,
  };
}

/**
 * Get subtitles for a video in the requested format.
 */
export async function getSubtitles(
  videoUrl: string,
  language?: string,
  format: 'json' | 'srt' | 'txt' = 'txt'
): Promise<SubtitleResult> {
  const videoId = extractVideoId(videoUrl);
  const playerResponse = await fetchPlayerResponse(videoId);
  const { tracks } = parseCaptionTracks(playerResponse);

  if (tracks.length === 0) {
    throw new SubtitleError('No subtitles available for this video', 'NO_SUBTITLES');
  }

  // Find the best matching track
  let selectedTrack: CaptionTrack | undefined;
  let needsTranslation = false;

  if (language) {
    // Exact match first
    selectedTrack = tracks.find((t) => t.languageCode === language);

    // If not found, check if we can translate
    if (!selectedTrack) {
      // Use the first available track and translate
      selectedTrack = tracks[0];
      needsTranslation = true;
    }
  } else {
    // Default: prefer manual over auto-generated
    selectedTrack = tracks.find((t) => t.kind !== 'asr') || tracks[0];
  }

  if (!selectedTrack?.baseUrl) {
    throw new SubtitleError('No subtitle track found with a valid URL', 'NO_TRACK_URL');
  }

  const targetLang = needsTranslation ? language : undefined;
  
  let data: YouTubeTimedTextResponse;
  let actualLang = '';
  let actualKind = '';
  
  try {
    const fetched = await fetchTimedText(selectedTrack.baseUrl, targetLang);
    data = fetched.data;
    actualLang = fetched.actualLang;
    actualKind = fetched.actualKind;
  } catch (err) {
    logger.warn('Direct fetch failed, checking MCP bridge cache...', { videoId });
    const cached = getAutoSubtitle(videoId);
    if (cached) {
      logger.info('Found subtitle in MCP bridge cache', { videoId });
      data = cached.data;
      actualLang = cached.language;
      actualKind = selectedTrack.kind === 'asr' ? 'asr' : 'manual';
    } else {
      throw new SubtitleError(
        'Failed to fetch directly from YouTube, and no subtitle found in MCP bridge cache. Please run open_youtube_video first to allow the Chrome extension to extract subtitles automatically.',
        'FETCH_FAILED'
      );
    }
  }

  const entries = parseEvents(data);

  if (entries.length === 0) {
    throw new SubtitleError('Subtitle track returned no entries', 'EMPTY_SUBTITLES');
  }

  const result: SubtitleResult = {
    videoId,
    videoTitle: playerResponse.videoDetails?.title || 'Unknown',
    language: actualLang,
    languageName: getLanguageName(actualLang),
    kind: actualKind === 'asr' ? 'auto-generated' : 'manual',
    entries,
    totalEntries: entries.length,
    format,
  };

  if (format === 'srt') {
    result.formatted = formatAsSRT(data);
  } else if (format === 'txt') {
    result.formatted = formatAsPlainText(data);
  }

  return result;
}
